"""update Medifile model to Snapshots

Revision ID: 7bfb5335d207
Revises: 15735b6d7859
Create Date: 2025-07-07 11:15:47.203409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfb5335d207'
down_revision: Union[str, None] = '15735b6d7859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mf_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('procedure_datetime', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_src', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_thumbnail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('file_status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('annotation_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='media_files_pkey')
    )
    # ### end Alembic commands ###
