"""added login_name in user table migration

Revision ID: 7fce09026ece
Revises: fe93cfb5e4bb
Create Date: 2025-12-05 23:04:42.836706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fce09026ece'
down_revision: Union[str, None] = 'fe93cfb5e4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_name', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_column('users', 'login_name')
    # ### end Alembic commands ###
