"""Initial migration

Revision ID: fe93cfb5e4bb
Revises: 0bb49954b1cc
Create Date: 2025-12-05 18:36:45.248199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe93cfb5e4bb'
down_revision: Union[str, None] = '0bb49954b1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
